### PR TITLE
Setting for removing received file

### PR DESCRIPTION
**Pull request by CODeRUS**

### CODE REVIEW

**Comment by tgalal** [comment]
Conversation.qml has syntax error

**Comment by CODeRUS** [comment]
sure, fixed

**Comment by tgalal** [comment]
-Works only after I receive a file then I restart Wazapp, otherwise Query dialog never and message is just deleted.
-When QueryDialog ask for confirmation to delete the media files, the media message is deleted anyway even if I hit no. Is that intended?

**Comment by CODeRUS** [comment]
media message deletes anyway, sure.
confirmation dialog for removing received media file also

**Comment by CODeRUS** [comment]
query dialog showed only for incoming messages with successfully downloaded media: image, audio, video

**Comment by CODeRUS** [comment]
is any wrongs?

**Comment by tgalal** [comment]
It doesn't show for me unless I restart wazapp after downloading the image.

I download 2 received media files , long tap the first one, options show, I hit remove message and it's gone, no query dialogs.. I restart Wazapp, long tap the second one previously downloaded, I hit remove, and the dialog shows.

**Comment by CODeRUS** [comment]
i see. something  should be fixed on donwnload success signals to write transfer_status to 2

**Comment by CODeRUS** [comment]
maybe leave it without query? just delete file if exists?
all methods i found are dirty.
problem in Conversation.qml myDelegate media property. BubbleDelegate.qml can't overwrite it for Conversations. and if check media.transfer_status from Conversation.qml it always return model.media.transfer_status, not BubbleDelegate's one.

**Comment by CODeRUS** [comment]
what about this way? added to settings. global.

**Pull request merged**
