### PR TITLE
Adding Israel to country codes

### PR DESCRIPTION
**Pull request by funkycode**
http://talk.maemo.org/showpost.php?p=1213297&postcount=1060

### CODE REVIEW

**Comment by mnns** [comment]
Was really unnecessary to remove Israel at first place.

If you really want to get into politics, lets also remove Syria for killing children, Pakistan for killing women, Egypt for counterfeiting elections, Iran for threatening the entire world and so on.

**Comment by funkycode** [comment]
max2005b, make a favor and shut the f$ up. Ok?
The only person who does it political now it's you. No one removed Israel, as noone added it at the beginning.
P.S. I'm Israeli btw and it's commit to add. Anyway, for now just do what was told on forum to use wazapp and say thank you to developer.

**Comment by mnns** [comment]
The original list of country codes is an open source csv file, don't fool yourself, someone deleted it intentionally.

**Comment by funkycode** [comment]
afaik added in last Cepi's build's

**Pull request closed without merging**
