### PR TITLE
Complex notifier fixies

### PR DESCRIPTION
**Pull request by CODeRUS**
change phonon category to Notification
setting volume before playing
added Chat feedbackId config file
added Chat notifications behaviour settings

### CODE REVIEW

**Comment by knobtviker** [comment]
I've tested and it works perfect.

**Comment by TMavica** [comment]
sorry mate, i misunderstand the meaning

**Comment by CODeRUS** [comment]
Current build following media (magneta) volume bar. It's wrong. Notifications shouldn't follow media volume, it should be same volume with system sounds (blue) volume bar.
This patch fixing it.

**Comment by TMavica** [comment]
thanks, let me try it

**Comment by CODeRUS** [comment]
seems to be totally fixed now :D

**Comment by TMavica** [comment]
sound test ?

**Comment by CODeRUS** [comment]
yup. sounds_test build contain these  fixies for testing

**Comment by TMavica** [comment]
abnormal 'click' sound with incoming message when playing music with headphone
also relaunch wazapp when it is in multitask or swiping down.

**Comment by CODeRUS** [comment]
cannot confirm that
beep sound pplaying when message from current active contact. focussed sound when meeting profile.

**Comment by TMavica** [comment]
Hv you try in ringing mode?

**Comment by soryuuha** [comment]
im using sound_test2 build. I noticed that the notification sound will be gone when I plugged in earphones. and also during earphones plugged in, Wazapp gave out full blast of volume notification.

**Comment by CODeRUS** [comment]
confirmed. sound not working with earphones. sadly.

**Comment by tgalal** [comment]
is it still not working with earphones?

**Comment by CODeRUS** [comment]
Working when using system chat notifier. this is the only solution i found

**Comment by tgalal** [comment]
I get no notification sound through earphones even when system chat notifier, is it normal for feedbackId chat?

Also for some reason now neither the blue volume bar nor the magenta one control volume, it just goes out at full level when not using system chat notifier, and wazapp in background

**Comment by CODeRUS** [comment]
double check it, i have earphones sounds when using system notifier and volume controlled by blue bar with wazapp notifier okay

**Comment by tgalal** [comment]
I doubled checked. Using System notifier, sound does go through earphones, but not while music is playing though. Maybe that's normal I'll check if other IMs like skype or gtalk are same. 

As for wazapp notifier, Silent works, Beep works, but regardless of its level within the Ringing range, it just plays at highest volume.

**Pull request merged**
