### PR TITLE
Update src/accounts/wazapp.message.new.conf

### PR DESCRIPTION
**Pull request by CODeRUS**
Organiser feedbackId for working LED Events and not produce any sounds by notification
prewiewIconId changed to wazapp one for popup

### CODE REVIEW

**Comment by jorgratar** [comment]
Could you please show me where to find the link to update Wazapp in my N9? I have 0.2.6 ver.

**Comment by CODeRUS** [comment]
here always fresh builds =)
https://www.dropbox.com/sh/jb00mbx6tldb33x/G08rB-Goso

**Comment by tgalal** [comment]
How would I pull if you deleted your branch :D?!

**Comment by CODeRUS** [comment]
i think you ignored it =)

**Comment by CODeRUS** [comment]
please make changes manually then =)

**Comment by tgalal** [comment]
done that ;)

**Pull request closed without merging**
