### PR TITLE
i18n

### PR DESCRIPTION
**Pull request by berdario**
I have a friend who owns a N9: he asked me if it was possible to translate your app :)

I'm unable to test directly my changes, but they should be quite straightforward...

I also created a related project on Transifex, you can try and see if it works ok for you:

https://www.transifex.net/projects/p/wazapp

if it's ok, let me know your username on transifex and I'll add you to the mantainers

### CODE REVIEW

**Comment by RobertMe** [comment]
You also seem to be missing the actual "binding" of the translation. You'll also need to load and set the translation. This is documented in the harmattan developer doc.: http://harmattan-dev.nokia.com/docs/library/html/guide/html/Developer_Library_Developing_for_Harmattan_Localising_applications.html

Yes, it seems like documentation on this part really is a mess. There seem to be a lot of documents describing something related to the translation part, but there doesn't seem to be a page where everything is documented in detail.

**Comment by berdario** [comment]
eh, yes... I actually did the bare minimum to be able to let people to start translating

as I said, I can't test the application on my own, and all the examples are in c++... the code to load the translation is very simple, but I'm not confident to blindly translate that into python without being able to test

I tried to install the meego sdk, but it requires lots of old libraries, like libmpfr1ldbl (superseded by libmpfr ) do you have any hint to install the sdk on a ubuntu 12.04 box without tracking down manually all the dependencies? (maybe I could add the whole 10.04 repositories, and apt-pin them to a lower priority... but that's more effort than I'd expect to do)

**Comment by RobertMe** [comment]
Hmm, yes, it's written in Python, and I'm nor a C++ expert (just using it 2, 3 months now, self learning), nor a Python expert (never used it, at all).

What I did to get a working environment was install the [Qt SDK](http://qt.nokia.com/downloads), this includes a Harmattan chroot, Qt Creator support for Harmattan (using the chroot and publishing to and debugging on the device), etc. But I don't know if it's possible to run Python code from within Qt Creator or the chroot.

To get back on topic. I think it's best to move the ts file to a new client/i18n directory. Because for every language there needs to be a .ts file (so tr_en.ts, tr_nl.ts, tr_fr.ts, tr_de.ts, ...) and every ts file needs to be "compiled" using lrelease to a .qm file. So per language there will be two files. So in the UI directory it would create a lot of unneeded clutter.

**Comment by Morpog** [comment]
Is this going to get integrated? There are already a few translations: https://www.transifex.net/projects/p/wazapp
If yes it could get posted at TMO to get more translators.

**Comment by RobertMe** [comment]
In the cepi branch I found some evidence of (Spanish?) translations (it's hidden away in commit 60bcf1c). But because of the lack of communication on this pull request and other pull requests, but still an active development on the cepi and dev branches I think it's going to be hart to get this integrated. Also when I look at the development in general (commit messages etc.) I think it's mainly getting developed by Tgalal and CepiPerez without them trying to be "open". No responses on pull requests, commit messages and general "open" development is a mess (big messy commits which contain a lot of changes, impossible to keep track of the development). This pull request, and the 60bcf1c commits are perfect examples of it. The pull request receives no (official) comments, and the mentioned commit contains an awful lot of changes, not only related to the commit message which says something about the SpeechBuble. No one can now this commit adds support for translations, without reading the actual diff of the commit (which of course no one does)

**Comment by berdario** [comment]
yes, it seems issues and pull requests are a bit neglected...
but this has been open sourced recently, and maybe it's only a matter of manpower: 50 issues could be too much for 2 guys to handle properly in their freetime

I'll try to nag directly tgalal by mail, pointing him to this pull request

**Comment by RobertMe** [comment]
There seem to be only 39 issues, and of those 15 are created by tgalal himself (to track progress/new features that should be added).

Also some information about how to develop would be nice. In general there is a lack of information about how to set up a working Python environment, so it would have been best for them to create a small description how to get everything set up. When there is some information about how to do some development work on Wazapp (setting up the environment being the main hurdle) it could attract more developers. Which means the app can go forward faster. And if they would have a more clean development (no massive commits with lots of changes), it would help others to better understand the code, track changes, et cetera.

If this all was a little bit better arranged I would for example like to help a little where possible. But because there is no information about how to setup the development environment, and the general "openness" is a bit messy it's really holding me back to help out.

**Comment by tgalal** [comment]
Hello. Sorry for not merging just yet, but I assure you they're absolutely not neglected, and as you see, there wasn't any release after pull was requested. It's just that I haven't pulled them in yet. But I also have to check with Perez since he is mainly handling the UI and recently added translation. If he used your stuff then this means it's already pulled and I'll close it. I appreciate all the work done by the awesome community and sorry for not having much docs around. I will focus on docs and portability to other platforms after the next release.

**Comment by berdario** [comment]
Ok, FYI, files like main.qml, seems to have been already i18n'ed, but others like Registration.qml aren't (thus it seems that this pull might still be useful)

**Comment by CepiPerez** [comment]
I'm working hard to translate all string, but seems I've missed some of them
Registration.qml is fixed now. Will be in the next commit.
Can you please tell me if there's more missing strings?

**Comment by tgalal** [comment]
@CepiPerez have you used the ones in this request for registration?

**Comment by CepiPerez** [comment]
Nop, I made translations by myself

**Comment by tgalal** [comment]
@CepiPerez  Is there a reason which made you not use the ones in this request for registration or is the one you did different from it?

**Comment by CepiPerez** [comment]
Because the translations here are taken from master branch, and it's outdated

**Comment by tgalal** [comment]
It's not outdated for Registration. Nothing changed in registration since 0.2.6 in master

**Comment by CepiPerez** [comment]
Ok sorry, then forgot what I said

**Comment by CepiPerez** [comment]
I've been looking at transifex, and the source is outdated
Please update it. Check the latest commit in dev branch

**Comment by tgalal** [comment]
Ok I want to get translation part to be more organized. I would like to suggest the following and @berdario, @RobertMe, @Morpog, @CepiPerez please give me your opinion on this. It would be inefficient to translate dev branch. Since it's a dev branch and is changing all the time. And I'm having all dev related work (including translation) to be made away from master. So what I would like suggest is that I'll create new branch (RC), which gets updated prior to each release. Translations should be updated against only this branch. Let me know what you think.

**Comment by tgalal** [comment]
@berdario my username on transifex is tgalal

**Comment by Morpog** [comment]
That RC branch for translating sounds like a good plan. But I'm no coder, just a translator / wazapp user. You should make sure that translators get notified when there is a new push to RC branch. Maybe transifex has an option for that?

**Comment by berdario** [comment]
Ok, I pulled the changes in branch cepi... merged my changes on master onto them (the code seems to be messy, with inconsistent usage of tabs and spaces... but apparently I resolved correctly the conflicts)
then I added some last qsTr calls that were missing and updated the wazapp.ts

finally: I uploaded the new .ts on transifex, added tgalal as maintainer on transifex as well, and opened a new pull request (this one directly on tgalal/cepi )

@CepiPerez for next time you may need this, to find out where there're other strings that could need i18n, I suggest ack:

http://betterthangrep.com/

and then you can run something like:

`ack-grep -a "[tT]ext:[\s]*\".*\""`

(the -a flag is to select all kind of files, since ack doesn't know about .qml files)

**Comment by berdario** [comment]
@tgalal @Morpog Having a separate branch for translations seems a sensible idea

Indeed, transifex supports to automatically update a resource (the english .ts )... but I haven't set it up yet, since these changes haven't been merged yet

about the other pull request: I've done it on /cepi since there still are unwrapped strings... as soon as the other one is merged we can close this request, but I'd continue to use this for discussion and I don't know if closing it now would hamper the discussion (e.g by disabling notifications?)

**Comment by RobertMe** [comment]
You could also do some kind of string freeze. After the string freeze there shouldn't be any changes in the texts, but you're still allowed to do some other changes, as long as they don't affect the texts. Then you could still use the dev branch, from which translators can do the translations, and others will still be able to do changes to the code, as long as they don't change the text.

But an RC branch is also a good idea. It would also enable you to do a RC release, without up to date translations, but others would than be able to do some testing. This enables more users to test a "not final" release so they can do some bughunting and the final could be more stable. The RC branch should then also be "freezed", only bugfixing (and translations) allowed. So development can still happen on the dev (and/or topic) branches, and bugfixes which should be fixed before release can be committed on the RC branch.

**Comment by tgalal** [comment]
Yup, RC would be for testing versions, and only bug fixes and translation updates are to be done there.
So sequence  is:

[dev branch]---going-for-new-release--->[RC branch] --tested-and-translated--->[master branch and package creation]

@berdario I merged the other one. If something goes wrong with discussion we can create a new issue and continue the discussion over there.

**Pull request closed without merging**
