### PR TITLE
just some minor fix

### PR DESCRIPTION
**Pull request by knobtviker**
switching from hardcoded coordinates to anchor layout

### CODE REVIEW

**Comment by tgalal** [comment]
Merged into dev branch. Btw, for some reason text in Speechbubble looks centered. Problem in width calc functions?

**Comment by knobtviker** [comment]
It is supposed to be centered only if message text is shorter than timestamp text. Otherwise anchored as usual.

**Comment by tgalal** [comment]
Oh so it's intended :) So why center it ? I personally think it looks better if always anchored to left.

**Comment by knobtviker** [comment]
I took a WP7, Symbian and Android device. On every official client, if text is shorter - it's centered. That was the main reason. Secondary was that users where complaining about wasting space on the right when messages are short.
Final solution would be (once Settings are in place) to allow users to switch layouts. Not everybody writes from left to right... :)

**Comment by tgalal** [comment]
ok cool :)

**Comment by knobtviker** [comment]
ok :) now reply to my (G)mail  please :D
I got more goodies :)

**Pull request closed without merging**
