### PR TITLE
Contact Page improvements

### PR DESCRIPTION
**Pull request by CODeRUS**
Media list
Groups list
SMS sending fix
Number displaying fix

### CODE REVIEW

**Comment by tgalal** [comment]
Did you test that code? (specifically contact page)

**Comment by CODeRUS** [comment]
Yes. Requested after build and install. Can share deb for testing =)
Or you can build my patch branch.

**Comment by CODeRUS** [comment]
uploaded to https://github.com/CODeRUS/wazapp/downloads

**Comment by tgalal** [comment]
An interesting thing I found sometime ago is that a contact's jid is sometimes not exactly the same as the number they registered with. Whatsapp could return a jid with a slightly modified number at registration. Therefore you can't assume the jid is always a real number. Instead, use the actual number property for a contact.

**Comment by tgalal** [comment]
oh and there is this: http://img407.imageshack.us/img407/2969/contactprofile.png
and that: 

file:///opt/waxmppplugin/bin/wazapp/UI/Contacts/ContactProfile.qml:192: ReferenceError: Can't find variable: separator2

in your build. Are you sure you tested? :P

**Comment by CODeRUS** [comment]
yes. i have some extra changes, commiting now.
just package broken

**Comment by CODeRUS** [comment]
"right" deb uploaded to https://github.com/CODeRUS/wazapp/downloads

**Comment by CODeRUS** [comment]
https://github.com/downloads/CODeRUS/wazapp/wazapp_0.8.11-issue164_armel.deb

**Pull request merged**
