### PR TITLE
Conversation message copy fix

### PR DESCRIPTION
**Pull request by CODeRUS**
*fixed copy to clipboard
*fixed insert emoji and linebreak after pasting message

### CODE REVIEW

**Comment by tgalal** [comment]
I get these errors if I try to paste:

ile:///usr/lib/qt4/imports/com/nokia/meego/EditBubble.js:170: TypeError: Result of expression 'popup.position' [undefined] is not an object.
file:///usr/lib/qt4/imports/com/nokia/meego/EditBubble.js:170: TypeError: Result of expression 'popup.position' [undefined] is not an object.

file:///usr/lib/qt4/imports/com/nokia/meego/EditBubble.js:170: TypeError: Result of expression 'popup.position' [undefined] is not an object.
file:///usr/lib/qt4/imports/com/nokia/meego/EditBubble.js:170: TypeError: Result of expression 'popup.position' [undefined] is not an object.
QClipboard::setData: Cannot set X11 selection owner for CLIPBOARD

However, they do in fact paste correctly, except for emoji which are pasted as boxes (not emojified?), they are sent correctly though.

**Comment by CODeRUS** [comment]
it always was here...shall i try to fix?

**Comment by CODeRUS** [comment]
seems to be internal Qt bug

**Comment by tgalal** [comment]
It's ok for those errors, but emoji are pasted as boxes, despite the fact that they are correctly sent. But is there a solution to them not being correctly pasted?

**Comment by CODeRUS** [comment]
there are no onPasted signal, so we can't handle it easy.
i tried to play inside onTextChanged, but it break cursor position every time.

**Comment by tgalal** [comment]
Okay, I'll merge it for now and will look into it later. Thanks a lot

**Comment by CODeRUS** [comment]
Sure, there are no reason not to use it now as is

**Pull request merged**
