### PR TITLE
i18n on branch cepi

### PR DESCRIPTION
**Pull request by berdario**
ditto

### CODE REVIEW

**Comment by RobertMe** [comment]
I think it would be best to rename wazapp.ts to tr_en.ts. This way the files have a unified name of tr_<language>.ts. I also think you should run lrelease on the ts file so the binary based translation is available. This .qm file (generated by lrelease) is also the file which gets loaded by Qt to use for the translation. Otherwise Qt uses the texts provided in the qsTr call and can't use the translation. For the English translation this of course isn't a problem, as the texts are the same, but it just adds to the consistency.

**Comment by berdario** [comment]
I think that naming it wazapp.ts might help to distinguishing it from all the other files: after all, it's the only one that has to be loaded on transifex

then again, if we create a .qm even for english, it may be better to keep it with the same name... what's the consensus on this?

**Comment by tgalal** [comment]
@CepiPerez Changes look good to me. Merge?

**Comment by tgalal** [comment]
@berdario @RobertMe Frankly I'm not so familiar with how translation works in QML. So for now it's mostly up to @CepiPerez. So Perez, let us know what you think? :)

**Comment by CepiPerez** [comment]
Yes, it all updated now :D

**Pull request merged**
